# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Publish Node.js Package

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      node_version:
        description: 'Node version to use'
        required: true
        default: '16'
      registry_url:
        description: 'NPM registry URL'
        required: true
        default: 'https://registry.npmjs.org/'
      scope:
        description: 'Scope for npm package'
        required: false
        default: ''
      access:
        description: 'Access level for npm package'
        required: false
        default: 'public'
      publish_to_gpr:
        description: 'Should publish to GitHub Package Registry'
        required: false
        type: boolean
        default: true

jobs:
  call-central-workflow:
    uses: openimis/openimis-fe_js/.github/workflows/module-npmpublish.yml@feature/central-publish-workflow
    with:
      node_version: '16'
      registry_url: 'https://registry.npmjs.org/'
      access: 'public'
      scope: 'openimis'
      publish_to_gpr: true
    secrets:
      TOKEN: ${{ secrets.NPM_TOKEN }}
      GPR_TOKEN: ${{secrets.GITHUB_TOKEN}}
